# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('institution_affiliation', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('location_elevation', models.CharField(blank=True, max_length=30, null=True)),
                ('location_kmz_url', models.URLField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                         to='archive_api.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_elevation', models.CharField(blank=True, max_length=30)),
                ('location_map_url', models.URLField(blank=True, null=True)),
                ('location_bounding_box_ul_latitude', models.FloatField(blank=True, null=True)),
                ('location_bounding_box_ul_longitude', models.FloatField(blank=True, null=True)),
                ('location_bounding_box_lr_latitude', models.FloatField(blank=True, null=True)),
                ('location_bounding_box_lr_longitude', models.FloatField(blank=True, null=True)),
                ('site_urls', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(to='archive_api.Contact')),
                ('pis', models.ManyToManyField(related_name='_site_pi_+', to='archive_api.Contact')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                 to='archive_api.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archive_api.Site'),
        ),
        migrations.AddField(
            model_name='plot',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='archive_api.Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name', 'institution_affiliation', 'email')},
        ),
    ]
