# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0003_ngt_resources_allow_nulls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementvariable',
            options={'ordering': ('name',)},
        ),
    ]
