# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:55
from __future__ import unicode_literals

import archive_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_api', '0005_alter_qaqc_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementvariable',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
